Dev101
kayacetinsu/kayacetinsu.techsoftwaredatabase.com pull request #18
Opened 2023-03-24 22:03 UTC by megassoft

this is final

2023-03-24 22:08 UTC, kayacetinsu reviewed
sure

2023-03-24 22:08 UTC, kayacetinsu commented on index.html
> +<!-- Dev 1 -->
we will revise it

2023-03-24 22:08 UTC, kayacetinsu commented on index.html
> +<!-- Dev 1 -->
ok

2023-03-24 22:12 UTC, megassoft reviewed
what can i do?

2023-03-24 22:12 UTC, megassoft commented on index.html
literally i added dev 2

2023-03-24 22:12 UTC, kayacetinsu commented on index.html
try to be specific

2023-03-24 22:16 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
is it okay?

2023-03-24 22:18 UTC, megassoft reviewed
i tried few things. check

2023-03-24 22:18 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
is that okay?

2023-03-24 22:18 UTC, megassoft commented on index.html
> -<!-- Main 1 -->
this is old one

2023-03-24 22:22 UTC, kayacetinsu reviewed
try again

2023-03-24 22:22 UTC, kayacetinsu commented on index.html
lets see

2023-03-24 22:22 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
yes

2023-03-24 22:22 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
not sure

2023-03-24 22:24 UTC, megassoft reviewed
hmm

2023-03-24 22:24 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
suggestion?

2023-03-24 22:27 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
we will add ver

2023-03-24 22:28 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
try?

2023-03-24 22:29 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
or

2023-03-24 22:29 UTC, megassoft commented on index.html
> +<!-- Dev 2 -->
let me do it

2023-03-24 22:42 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
awesome. done!

2023-03-24 22:43 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
lets publish

2023-03-24 22:44 UTC, kayacetinsu approved these changes
great! done

2023-03-24 22:44 UTC, kayacetinsu commented on index.html
> +<!-- Dev 2 -->
done!

2023-03-24 22:46 UTC, kayacetinsu approved these changes
push

2023-03-24 22:51 UTC, kayacetinsu requested changes
try

2023-03-24 22:53 UTC, kayacetinsu approved these changes
total

2023-03-24 22:55 UTC, kayacetinsu requested changes
again

2023-03-24 22:57 UTC, kayacetinsu approved these changes

2023-03-25 00:05 UTC, kayacetinsu requested changes
try

2023-03-25 00:07 UTC, kayacetinsu approved these changes

2023-03-25 00:08 UTC, merged